Repository udistrital/parametros_estandar_crud, pull requests merged in 2019-11, with the labels that each got.

#2 Dev
  README.md
Labels: bug

#3 Correr Drone
  README.md
Labels: bug

#4 Se agrega modelo de tabla Periodo y se re despliega para que queden v…
  sql/parametros_estandar_schema.sql
Labels: bug, enhancement

#5 Se agrega tabla de periodo
  database/migrations/20191127_120059_crear_tabla_periodo.go
  sql/parametros_estandar_schema.png
Labels: enhancement
